server {
    # Указываем порт, который Traefik ожидает по переменной CLIENT_NGINX_PORT
    listen 4020;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Критически важная строка для React-приложений (SPA)!
        # Если пользователь перезагрузит страницу тренажера (например, /exercises/level3),
        # Nginx не выдаст ошибку 404, а мягко перенаправит запрос на index.html,
        # где управление заберет твой локальный React Router.
        try_files $uri $uri/ /index.html;
    }

    # Логирование ошибок и базовая заглушка
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
